### PR TITLE
Handle 8 and 12 MHz HSE values

### PR DESCRIPTION
**Pull request by fpistm**
Hi @darkspr1te 
This PR handle 8 and 12MHz system clock config.
If you can test and think it is OK then you can merge in your branch and I will be able to merge your PR in official repo.
Thanks in advance for your feedback.

### CODE REVIEW

**Comment by fpistm** [comment]
Did you test it?

**Comment by darkspr1te** [comment]
yes, working fine with my setup but not with the new offical core, i need to check on that later, could be a conflict with my local base as I am also trying to port some of the functions from other stmduino cores so often run sandboxed setups that are not full environments. the symptom is hanging when using hardware timers. Again, could be a issue with my multi core setup or the newly added h/w timers, my test projects use h/w timers but from my own code base,

**Comment by fpistm** [comment]
ok

**Comment by darkspr1te** [comment]
Issue resolved and it was with my local code. 8mhz and 12mhz works on both my official boards (8/12mhz external xtal only). This will cover a lot of cleanflight based boards on the current market.

**Pull request merged**
